[[battery.display]]
threshold = 10
style = "red"
[[battery.display]]
threshold = 20
style = "purple"
[[battery.display]]
threshold = 40
style = "yellow"

[git_branch]
symbol = "ï˜ "

[git_status]
modified = "!${count}"
staged= "+${count}"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[localip]
disabled = false
ssh_only = false

[memory_usage]
disabled = false

[python]
python_binary = ["python3", "python"]

[sudo]
disabled = false

[terraform]
format = "ğŸª[$version]($style) "

[time]
disabled = false
format = "[$time]($style) "
