[git_branch]
symbol = "ï˜ "

[git_status]
modified = "!${count}"
staged= "+${count}"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[python]
python_binary = ["python3", "python"]

[sudo]
disabled = false

[terraform]
format = "ğŸª[$version]($style) "

[time]
disabled = false
format = "[$time]($style) "
